#' datsim: A simulated data set for image mediation analysis
#'
#' This data set is generated by STGP_generate_theta_block function using the same cammond as in ./docs/BIMA_example.Rmd
#' This data sets contains 4 regions for 2D image.
#'
#' @name datsim
#' @format A list object that contains both the data and the true parameters. n = 300, p=400
#' \describe{
#'   \item{Y}{scalar outcome, n by 1}
#'   \item{M}{Image mediator, p by n}
#'   \item{X}{Exposure variable, n by 1}
#'   \item{C}{q Confounder variables, q by n}
#'   \item{....}{All other components are true parameters used to generate the data set. }
#' }
NULL

#' one_region: A simulated data with 1 region for image mediation analysis
#'
#' This data set is generated by STGP_generate_theta_block function using the same cammond as in ./docs/small_example.Rmd
#' This data sets contains 1 regions for 2D image.
#'
#' @name one_region
#' @format A list object that contains both the data and the true parameters. n = 300, p=400
#' \describe{
#'   \item{Y}{scalar outcome, n by 1}
#'   \item{M}{Image mediator, p by n}
#'   \item{X}{Exposure variable, n by 1}
#'   \item{C}{q Confounder variables, q by n}
#'   \item{beta_test_ST}{True image used to generate beta}
#'   \item{alpha_test_ST}{True image used to generate alpha}
#'   \item{....}{All other components are true parameters used to generate the data set. }
#' }
NULL


